### PR TITLE
Frontend

### LINKED ISSUE #17: Player data message sending without username if it is changed
If a player changes their username, any subsequent player_data messages sent will not include the username field. In this example, 4 players join a lobby, and the 4th changes their username to something valid. A 5th player joins, and as can be seen, their username field in the player_data message does not appear while it is fine for the rest of the players.
Screenshot from 2021-11-08 11-21-10
e

### PR DESCRIPTION
**Pull request by robbiehammond**
Re-added frontend functionality with support for multiple lobbies, player join/leave, and username changes. Setup for not-yet-implemented functionality also added. Also added the restartServer script, which has a self-explanatory purpose.

### CODE REVIEW

**Comment by edf42001** [comment]
Can you add the colors? Something like "`document.getElementById(clone.id).getElementsByClassName('dot')[0].style = `background-color: ${player.color};`"?

**Comment by edf42001** [comment]
A bit more tricky but still very short: Can you add the link? When the client recieves it's first message, now it knows the lobby id and it should put the text `http://3.144.98.109/?lobbyID` on the screen. To make this work, at the start of the client code, check the value of `window.location.search`. If its non empty, that represents the lobbyID after the `?` and the client should auto send the lobby join message that is currently being sent by that input box.

**Comment by robbiehammond** [comment]
> Can you add the colors? Something like "`document.getElementById(clone.id).getElementsByClassName('dot')[0].style = `background-color: ${player.color};`"?

> A bit more tricky but still very short: Can you add the link? When the client recieves it's first message, now it knows the lobby id and it should put the text `http://3.144.98.109/?lobbyID` on the screen. To make this work, at the start of the client code, check the value of `window.location.search`. If its non empty, that represents the lobbyID after the `?` and the client should auto send the lobby join message that is currently being sent by that input box.

Def can do both, but I wouldn't be able to get it done today. I could get it done tomorrow evening or Wednesday morning

**Comment by andrew0144** [comment]
> A bit more tricky but still very short: Can you add the link? When the client recieves it's first message, now it knows the lobby id and it should put the text `http://3.144.98.109/?lobbyID` on the screen. To make this work, at the start of the client code, check the value of `window.location.search`. If its non empty, that represents the lobbyID after the `?` and the client should auto send the lobby join message that is currently being sent by that input box.

Can you explain more of what you mean by "the client should auto send the lobby join message that is currently being sent by that input box"? I have added an HTML element displaying the lobby but I don't know what you mean by this exactly.Thanks!

**Comment by edf42001** [comment]
You know the `lobbyID` input box, next to the `Join` button? This calls `onJoin` (I believe, from skimming the code). We want this to be automatic when the user types `url/?lobbyID` but not if they just type `url`. So the code gets moved up to the start of the script, and reads the `?lobbyID` string from the URL. If it's not empty, it calls the `onJoin` code. Otherwise the player just hangs out on the main page.

**Comment by robbiehammond** [comment]
Just did a 100% world record speedrun of the link joining functionality. Is something like what I commited (and what is also on the server) what you're looking for Ethan?

**Comment by robbiehammond** [comment]
Just performed a 100% glitchless non-emulator link addition to the HTML in 2:53.59. Lost about 45 seconds on the index.html level, but made it back up on the client.js boss fight. Also, I got rid of lobby join button and the accompanying text box. Code is currently on the server. Is there anything else we should add/fix?

**Review by edf42001 — APPROVED** [review]
After careful review, I have decided to accept this speedrun into the records. Other things such as settings, ready, indicating who you are, indicating the lobby owner, need to be done, but this will be merged first.

**Pull request merged**
